// Actions relating to Currencies
export const FETCHED_CURRENCIES = 'FETCHED_CURRENCIES';
export const CURRENCIES_FETCH_FAILED = 'CURRENCIES_FETCH_FAILED';
export const CURRENCIES_FETCH_START = 'CURRENCIES_FETCH_START';
